ALTER TABLE "share_groups" ADD COLUMN IF NOT EXISTS "themePreset" TEXT;
ALTER TABLE "share_groups" ADD COLUMN IF NOT EXISTS "customTheme" TEXT;
ALTER TABLE "share_groups" ADD COLUMN IF NOT EXISTS "logoText" TEXT;
ALTER TABLE "share_groups" ADD COLUMN IF NOT EXISTS "logoImageId" UUID REFERENCES "logos"("id") ON DELETE SET NULL;
ALTER TABLE "share_groups" ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
